name: .NET Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Bison.CLI/Bison.CLI.csproj
      - name: Build
        run: dotnet build Bison.CLI/Bison.CLI.csproj --no-restore
      - name: Test
        run: dotnet test Bison.CLI/Bison.CLI.csproj --no-build --verbosity normal
